isnan{T<:SysFloat}(a::FloatFloat{T})       = isnan(a.hi)
isinf{T<:SysFloat}(a::FloatFloat{T})       = isinf(a.hi)
isfinite{T<:SysFloat}(a::FloatFloat{T})    = isfinite(a.hi)
issubnormal{T<:SysFloat}(a::FloatFloat{T}) = issubnormal(a.hi)

iszero{T<:SysFloat}(a::FloatFloat{T})    = (a.hi == zero(T))
isnonzero{T<:SysFloat}(a::FloatFloat{T}) = (a.hi != zero(T))
ispos{T<:SysFloat}(a::FloatFloat{T})     = (a.hi >= zero(T))
isneg{T<:SysFloat}(a::FloatFloat{T})     = signbit(a.hi)
isnonneg{T<:SysFloat}(a::FloatFloat{T})  = !signbit(a.hi)
