isnan{T<:StdFloat}(a::FF{T})       = isnan(a.hi)
isinf{T<:StdFloat}(a::FF{T})       = isinf(a.hi)
isfinite{T<:StdFloat}(a::FF{T})    = isfinite(a.hi)
issubnormal{T<:StdFloat}(a::FF{T}) = issubnormal(a.hi)

iszero{T<:StdFloat}(a::FF{T})    = (a.hi == zero(T))
isnonzero{T<:StdFloat}(a::FF{T}) = (a.hi != zero(T))
ispos{T<:StdFloat}(a::FF{T})     = (a.hi >= zero(T))
isneg{T<:StdFloat}(a::FF{T})     = signbit(a.hi)
isnonneg{T<:StdFloat}(a::FF{T})  = !signbit(a.hi)
